### ISSUE TITLE
Guideline for collaborative workflow

### ISSUE THREAD

**Issue by rishikeshsjoshi** [awegroup/AWE-Eco#15]
To accept contributions from external contributors in future as we want to keep the code live. This code is attached to a published version of a report. How to log the key improvements in the code against the published version of the report?

**Comment by mwakok** [comment]
You can address this with two documents:

1. A [Contributing guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) that documents how external contributors can contribute. I often this example as my starting point: https://github.com/matchms/matchms/blob/master/CONTRIBUTING.md
2. A [Changelog](https://keepachangelog.com/en/1.1.0/) where you document the changes of each release of your software. See the same repository for an example: https://github.com/matchms/matchms/blob/master/CHANGELOG.md.
    - A changelog will make most sense if you follow a [release workflow](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository). This will also allow you to be able to quickly find the published version of the software. 

You will need to decide yourself how you would like external developers to contribute and how you will maintain and support the software in the future.
